apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pinniped-supervisor
  namespace: {{ .Values.namespace | default "pinniped-supervisor" | lower }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.host | replace "." "-" }}-cert
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pinniped-supervisor
            port:
              number: 80