apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace | default "pinniped-supervisor" | lower }}
  name: pinniped-supervisor
spec:
  selector:
    app: pinniped-supervisor
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP