apiVersion: v1
name: pinniped-supervisor
description: The Supervisor is an OpenID Connect (OIDC) issuer that supports connecting a single “upstream” OIDC identity provider to many “downstream” cluster clients.
appVersion: "v0.7.0"
version: 1.0.0